horses/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'horses.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^racing/', include('racing.urls', namespace='racing')),
    url(r'^admin/', include(admin.site.urls)),

)

racing/urls.py
from django.conf.urls import patterns, url

from racing import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^layem/$', views.layem, name='layem'),
                       url(r'^(?P<meeting_id>\d+)/$', views.meeting_detail, name='meeting_detail'),
                       url(r'^update/$', views.update, name='update'),
                       url(r'^delete_todays_meetings/$', views.delete_todays_meetings, name='delete_todays_meetings'),
)

racing/models.py
from django.db import models


class Meeting(models.Model):
    date = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['date', 'name']


class Horse(models.Model):
    forecast = models.DecimalField(default=0, max_digits=4, decimal_places=1)
    last_run = models.IntegerField(default=0)
    name     = models.CharField(max_length=200)
    number   = models.IntegerField(default=0)
    weight   = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['number']


class Race(models.Model):
    date     = models.DateTimeField()
    distance = models.IntegerField(default=0)
    going    = models.CharField(max_length=50)
    horses   = models.ManyToManyField(Horse)
    meeting  = models.ForeignKey(Meeting)
    name     = models.CharField(max_length=200)
    runners  = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['date']

racing/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, get_list_or_404
from datetime import datetime, timedelta
from racing.models import Meeting, Race, Horse
from collections import OrderedDict

def index(request):
    meetings = Meeting.objects.filter(date__gte=(datetime.today() - timedelta(days=2)))
    meeting_dates = set([m.date for m in meetings])             # Create a set of meeting dates.
    meetings_separated = dict([(d, []) for d in meeting_dates]) # Initialise an empty list for each date.
    for d in meeting_dates:                                     # Separate out the meetings into a
        for m in meetings:                                      # dictionary by index date with a list of meetings.
            if m.date == d:
                meetings_separated[d].append(m)
    meetings_separated = OrderedDict(sorted(meetings_separated.items(), reverse=True))
    return render(request, 'racing/index.html', {"meetings_separated": meetings_separated})

def meeting_detail(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    races = get_list_or_404(Race, meeting=meeting)
    return render(request, 'racing/meeting_detail.html', {'meeting': meeting, 'races': races})

def layem(request):
    races = Race.objects.filter(meeting__date=datetime.today())
    races = races.filter(distance__lt=2200, distance__gte=0)
    races = races.filter(runners__lte=16, runners__gte=11)
    races = races.filter(name__icontains='handicap')
    races = races.filter(
        Q(going__icontains='standard') | Q(going__icontains='good')
    )
    races = races.exclude(name__icontains='chase').exclude(name__icontains='hurdle')

    for race in races:
        race.horses = race.horses.exclude(number__lte=5)
        race.horses = race.horses.filter(last_run__gte=8)
        race.horses = race.horses.filter(forecast__gte=5, forecast__lte=8.5)

    return render(request, 'racing/layem.html', {'races': races})

def update(request):
    # For a waiting page use celery.
    from parsers.horses import get_todays_racecards, parse
    racecards = get_todays_racecards()
    meetings = []
    for racecard in racecards:
        meeting = parse(racecard)
        meetings.append(meeting)

        m = Meeting(name=meeting.name, date=datetime.today().date())
        m.save()

        for race in meeting.races:
            yards = race.get_distance_in_yards()
            rtime = datetime.strptime(race.time + " pm", "%I:%M %p")
            rdate = datetime.today().date()
            r = Race(
                date=datetime.combine(rdate, rtime.time()),
                distance=yards,
                going=race.going,
                meeting=m,
                name=race.name,
                runners=race.runners)
            r.save()

            for horse in race.horses:
                h = Horse(
                    forecast=horse.forecast_odds_decimal(),
                    last_run=horse.last_run,
                    name=horse.name,
                    number=horse.number,
                    weight=horse.weight)
                h.save()

                r.horses.add(h)

    return redirect('racing:index')

def delete_todays_meetings(request):
    meetings = Meeting.objects.filter(date=datetime.today().date())
    for meeting in meetings:
        meeting.delete()

    return redirect('racing:index')

racing/templates/racing/index.html
<form action="{% url 'racing:update' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Update" />
</form>


<form action="{% url 'racing:delete_todays_meetings' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% if meetings_separated %}
    {% for day, meetings in meetings_separated.items %}
        <h4>{{ day }}</h4>
        <ul>
        {% for meeting in meetings %}
            <li><a href='{% url 'racing:meeting_detail' meeting.id %}'>{{ meeting.name }}</a></li>
        {% endfor %}
        </ul>
    {% endfor %}
{% else %}
    <p>Nothing</p>
{% endif %}

racing/templates/racing/layem.html
{% if races %}
    <ul>
    {% for race in races %}
    {% if race.horses.all|length != 0 %}
        <li>{{ race.date|date:"g:i A" }} - {{ race.name }}</li> 
        <ul>
            <li>distance: {{ race.distance }} yards</li>
            <li>going: {{ race.going }}</li>
            <li>runners: {{ race.runners }}</li>
            <li>{{ race.meeting }}</li>
            <ul>
            {% for horse in race.horses.all %}
            <li>{{ horse.number }} - {{ horse.name|lower|capfirst }} - odds:{{ horse.forecast }}- ran:{{ horse.last_run }}</li>
            {% endfor %}
            </ul>
        </ul>
    {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No qualifiers for this system today.</p>
{% endif %}

racing/templates/racing/meeting_detail.html
{% if meeting %}
<h4>{{ meeting.name }} - {{ meeting.date|date:"l jS F Y" }}</h4>
    {% if races %}
        <ul>
        {% for race in races %}
        <li>{{ race.date|date:"g:i A" }} -  {{ race.name }} (going: {{ race.going }})</li>
        {% endfor %}
        </ul>
    {% endif %}
{% else %}
    <h4>Nothing</h4>
{% endif %}